name = "BacenDRM"
uuid = "08be8b77-4441-403f-b806-be951d3eff05"
authors = ["lucasprocessi <lucasprocessi@gmail.com>"]
version = "0.3.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]
EzXML = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
